version: '2'

services:

  tensorflow_and_pytorch:
    build: .
    container_name: tensorflow_and_pytorch
    # ports:
    # Mapping ports should not be done if we do not want to expose the service to the internet
    #   - 8888:8888
    user: $NB_UID:$NB_GID
    working_dir: /home/${NB_USER}
    volumes:
      - ${NOTEBOOKS_FOLDER}:/home/${NB_USER}
      - ./notebooks:/home/${NB_USER}/repository_notebooks
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    command: bash -c "conda init && echo 'conda activate pytorch' >> ~/.bashrc && jupyter notebook --port=8888 --ip=0.0.0.0 --NotebookApp.base_url='tensorflow_and_pytorch'"
    environment:
      - JUPYTER_CONFIG_DIR=/home/${NB_USER}
    labels:
      - log.level=debug
      - traefik.enable=true
      - traefik.frontend.rule=Host:${HOSTNAME};PathPrefix:/tensorflow_and_pytorch/
      - traefik.frontend.auth.basic=${ML_HTTP_USER}:${ML_HTTP_AUTH_PASS_ENC}
    depends_on:
      - traefik

  tensorboard:
    build: .
    container_name: tensorboard
    user: $NB_UID:$NB_GID
    working_dir: /home/${NB_USER}
    volumes:
      - ${NOTEBOOKS_FOLDER}:/home/${NB_USER}
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    #ports:
    # Mapping ports should not be done if we do not want to expose the service to the internet
    #  - 6006:8888
    command: tensorboard --logdir=tensorboard/runs --port=8888 --bind_all --path_prefix=/tensorboard/
    ipc: host
    labels:
      - log.level=debug
      - traefik.enable=true
      - traefik.frontend.rule=Host:${HOSTNAME};PathPrefix:/tensorboard/
      - traefik.frontend.auth.basic=${ML_HTTP_USER}:${ML_HTTP_AUTH_PASS_ENC}
    depends_on:
      - tensorflow_and_pytorch
      - traefik
